// sampleで使用
export const SAMPLE_INPUT_TEXT: "SAMPLE_INPUT_TEXT" = "SAMPLE_INPUT_TEXT";
export const SAMPLE_CHANGE_PULL_DOWN: "SAMPLE_CHANGE_PULL_DOWN" =
  "SAMPLE_CHANGE_PULL_DOWN";
export const SAMPLE_INSERT_REQUEST: "SAMPLE_INSERT_REQUEST" =
  "SAMPLE_INSERT_REQUEST";
export const SAMPLE_INSERT_SUCCESS: "SAMPLE_INSERT_SUCCESS" =
  "SAMPLE_INSERT_SUCCESS";
export const SAMPLE_DELETE_REQUEST: "SAMPLE_DELETE_REQUEST" =
  "SAMPLE_DELETE_REQUEST";
export const SAMPLE_DELETE_SUCCESS: "SAMPLE_DELETE_SUCCESS" =
  "SAMPLE_DELETE_SUCCESS";
export const SAMPLE_FETCH_REQUEST: "SAMPLE_FETCH_REQUEST" =
  "SAMPLE_FETCH_REQUEST";
export const SAMPLE_FETCH_SUCCESS: "SAMPLE_FETCH_SUCCESS" =
  "SAMPLE_FETCH_SUCCESS";
