// sample
export const SAMPLE_INPUT_TEXT: "SAMPLE_INPUT_TEXT" = "SAMPLE_INPUT_TEXT";
export const SAMPLE_CHANGE_PULL_DOWN: "SAMPLE_CHANGE_PULL_DOWN" =
  "SAMPLE_CHANGE_PULL_DOWN";
export const SAMPLE_INSERT_REQUEST: "SAMPLE_INSERT_REQUEST" =
  "SAMPLE_INSERT_REQUEST";
export const SAMPLE_INSERT_SUCCESS: "SAMPLE_INSERT_SUCCESS" =
  "SAMPLE_INSERT_SUCCESS";
export const SAMPLE_DELETE_REQUEST: "SAMPLE_DELETE_REQUEST" =
  "SAMPLE_DELETE_REQUEST";
export const SAMPLE_DELETE_SUCCESS: "SAMPLE_DELETE_SUCCESS" =
  "SAMPLE_DELETE_SUCCESS";
export const SAMPLE_FETCH_REQUEST: "SAMPLE_FETCH_REQUEST" =
  "SAMPLE_FETCH_REQUEST";
export const SAMPLE_FETCH_SUCCESS: "SAMPLE_FETCH_SUCCESS" =
  "SAMPLE_FETCH_SUCCESS";

// app
export const APP_FETCH_REQUEST: "APP_FETCH_REQUEST" = "APP_FETCH_REQUEST";
export const APP_FETCH_ERROR: "APP_FETCH_ERROR" = "APP_FETCH_ERROR";
export const APP_FETCH_SUCCESS: "APP_FETCH_SUCCESS" = "APP_FETCH_SUCCESS";

// login
export const LOGIN_INPUT_ID: "LOGIN_INPUT_ID" = "LOGIN_INPUT_ID";
export const LOGIN_INPUT_PASSWORD: "LOGIN_INPUT_PASSWORD" =
  "LOGIN_INPUT_PASSWORD";
export const LOGIN_HANDLE_LOGIN_REQUEST: "LOGIN_HANDLE_LOGIN_REQUEST" =
  "LOGIN_HANDLE_LOGIN_REQUEST";
export const LOGIN_HANDLE_LOGIN_ERROR: "LOGIN_HANDLE_LOGIN_ERROR" =
  "LOGIN_HANDLE_LOGIN_ERROR";
export const LOGIN_HANDLE_LOGIN_SUCCESS: "LOGIN_HANDLE_LOGIN_SUCCESS" =
  "LOGIN_HANDLE_LOGIN_SUCCESS";

// header
export const HEADER_FETCH_REQUEST: "HEADER_FETCH_REQUEST" =
  "HEADER_FETCH_REQUEST";
export const HEADER_FETCH_ERROR: "HEADER_FETCH_ERROR" = "HEADER_FETCH_ERROR";
export const HEADER_FETCH_SUCCESS: "HEADER_FETCH_SUCCESS" =
  "HEADER_FETCH_SUCCESS";

// rightNavi
export const RIGHT_NAVI_OPEN: "RIGHT_NAVI_OPEN" = "RIGHT_NAVI_OPEN";
export const RIGHT_NAVI_CLOSE: "RIGHT_NAVI_CLOSE" = "RIGHT_NAVI_CLOSE";

// leftNavi
export const HANDLE_LEFT_NAVI: "HANDLE_LEFT_NAVI" = "HANDLE_LEFT_NAVI";

// attendance
export const ATTENDANCE_FETCH_REQUEST: "ATTENDANCE_FETCH_REQUEST" =
  "ATTENDANCE_FETCH_REQUEST";
export const ATTENDANCE_FETCH_ERROR: "ATTENDANCE_FETCH_ERROR" =
  "ATTENDANCE_FETCH_ERROR";
export const ATTENDANCE_FETCH_SUCCESS: "ATTENDANCE_FETCH_SUCCESS" =
  "ATTENDANCE_FETCH_SUCCESS";
export const ATTENDANCE_CHANGE_PREV_REQUEST: "ATTENDANCE_CHANGE_PREV_REQUEST" =
  "ATTENDANCE_CHANGE_PREV_REQUEST";
export const ATTENDANCE_CHANGE_PREV_ERROR: "ATTENDANCE_CHANGE_PREV_ERROR" =
  "ATTENDANCE_CHANGE_PREV_ERROR";
export const ATTENDANCE_CHANGE_PREV_SUCCESS: "ATTENDANCE_CHANGE_PREV_SUCCESS" =
  "ATTENDANCE_CHANGE_PREV_SUCCESS";
export const ATTENDANCE_CHANGE_NEXT_REQUEST: "ATTENDANCE_CHANGE_NEXT_REQUEST" =
  "ATTENDANCE_CHANGE_NEXT_REQUEST";
export const ATTENDANCE_CHANGE_NEXT_ERROR: "ATTENDANCE_CHANGE_NEXT_ERROR" =
  "ATTENDANCE_CHANGE_NEXT_ERROR";
export const ATTENDANCE_CHANGE_NEXT_SUCCESS: "ATTENDANCE_CHANGE_NEXT_SUCCESS" =
  "ATTENDANCE_CHANGE_NEXT_SUCCESS";

// attendanceEdit
export const ATTENDANCE_EDIT_OPEN: "ATTENDANCE_EDIT_OPEN" = "ATTENDANCE_EDIT_OPEN";
export const ATTENDANCE_EDIT_CLOSE: "ATTENDANCE_EDIT_CLOSE" = "ATTENDANCE_EDIT_CLOSE";
