// sampleで使用
export const SAMPLE_INSERT_REQUEST: "SAMPLE_INSERT_REQUEST" =
  "SAMPLE_INSERT_REQUEST";
export const SAMPLE_INSERT_SUCCESS: "SAMPLE_INSERT_RESULT" =
  "SAMPLE_INSERT_RESULT";
export const SAMPLE_DELETE_REQUEST: "SAMPLE_DELETE_REQUEST" =
  "SAMPLE_DELETE_REQUEST";
export const SAMPLE_DELETE_SUCCESS: "SAMPLE_INSERT_REQUEST" =
  "SAMPLE_INSERT_REQUEST";
